# Generated by Django 3.1.3 on 2020-12-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
