# Generated by Django 3.1.3 on 2020-12-10 09:38

from django.db import migrations


def add_field(apps, schema_editor):
    Offer = apps.get_model('app', 'Offer')
    for offer in Offer.objects.all():
        offer.username = '%s' % offer.user.username
        offer.save


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201204_1310'),
    ]

    operations = [
        migrations.RunPython(add_field),
    ]
