# Generated by Django 3.1.3 on 2020-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201218_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('SELL', 'sell'), ('BUY', 'buy')], max_length=255),
        ),
    ]
